### ISSUE TITLE
Ablout mask calculation

### ISSUE THREAD

**Issue by hahahaprince** [chxy95/HDRTVNet#10]
Hi, thank you for your great work! 
I have some question about the mask calculation in highlight generation. As discribed in Figure 2 in your paper, the mask is computed from original SDR image, but I found it is computed from LE output in your code. So which one should we use?  As I realized, the non-linear RGB value  in HDR image is hardly more than 0.95.

https://github.com/chxy95/HDRTVNet/blob/41d63b58bb953a83fcd1666d77848945a261fb06/codes/data/LQGT_hallucination_dataset.py#L77

**Comment by chxy95** [comment]
@chxy95 Actually the mask is calculated from the original SDR image. I generete the masks of the input SDR images in mask_folder in advance then read the masks from the mask folder.

**Comment by chxy95** [comment]
@hahahaprince It seems an error in the released version, I will correct it soon.

**Comment by hahahaprince** [comment]
Okay, I get it. Thanks
