### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by kepengxu** [chxy95/HDRTVNet#14]
请问可以提供可以下载好的原始SDR视频与HDR视频吗，
我们发现部分链接已经实效了
感谢

**Comment by chxy95** [comment]
@kepengxu 请提供一下失效视频的信息

**Comment by chxy95** [comment]
@kepengxu 另外你们这篇SDRTV-to-HDRTV via Hierarchical Dynamic Context Feature Mapping文章对HDRTVNet的引用格式好像是有问题，Google Scholar的citation没有显示该文的引用。有时间麻烦check一下~

**Comment by kepengxu** [comment]
> @kepengxu 请提供一下失效视频的信息



> @kepengxu 另外你们这篇SDRTV-to-HDRTV via Hierarchical Dynamic Context Feature Mapping文章对HDRTVNet的引用格式好像是有问题，Google Scholar的citation没有显示该文的引用。有时间麻烦check一下~

好的，谢谢啦

**Comment by kepengxu** [comment]
> SDRTV-to-HDRTV via Hierarchical Dynamic Context Feature Mapping

好的，我检查一下这个问题

**Comment by kepengxu** [comment]
> > SDRTV-to-HDRTV via Hierarchical Dynamic Context Feature Mapping
> 
> 好的，我检查一下这个问题

多谢提醒啦

**Comment by kepengxu** [comment]
> @kepengxu 请提供一下失效视频的信息

https://www.youtube.com/watch?v=PxdZcvhtwzc
https://www.youtube.com/watch?v=W8oyStWkoSE&t=7s
https://www.youtube.com/watch?v=xtmbLFwR19o
https://www.youtube.com/watch?v=0rTv2EGmjqI
https://www.youtube.com/watch?v=T3-_RW99h3U
这五个视频链接无法下载了

**Comment by chxy95** [comment]
@kepengxu 留个邮箱我发给你

**Comment by kepengxu** [comment]
> @kepengxu 留个邮箱我发给你

kepengxu11@gmail.com
非常感谢啦
