### ISSUE TITLE
Reproduced results of previous works

### ISSUE THREAD

**Issue by tnt-ooo-tnt** [chxy95/HDRTVNet#2]
Hi, I am really glad to see your beautiful works.

I have got some questions here.

In _Figure 1_, (b), (c) and (d) can be counted as the categories of methods.
It also shows how you reproduced your results on _Table 1_.
In _Table 1_, it divides methods in 4 categories (LDR-to-HDR, image-to-image translation, photo retouching, and SDRTV-to-HDRTV).

I am little bit confused where image-to-image translation and photo retouching belong to.

1) Are they all end-to-end methods?

In data manipulation scripts, I could find a python script and a matlab script.

First, the python script crops 480x480 patches from inputs with step size 240.
Next, the matlab script produces mod, bicubic-downsampled, and bicubic-upsampled images.

2) I want to know the exact description of the accurate usage of each processed image like the location (which network to feed) of each dataset.

(I am confused with the paths named LE_training_set_res_sub, LE_test_set_res_bicx4, test_hdr_bicx4 .. etc)

Thank you for your reply in advance.

**Comment by tnt-ooo-tnt** [comment]
+
Best of my knowledge, the official implementation of Deep SR-ITM is written in matlab code.
Is the reproduced results of Deep SR-ITM using python version?

**Comment by chxy95** [comment]
@tnt-ooo-tnt 'end-to-end' here is to compare with the previous 'LDR-to-HDR' methods. We emphasize this point is to illustrate the difference between the task of LDR-to-HDR and SDRTV-to-HDRTV (i.e. SDR-to-HDR10 in this papre). From this perspective, image-to-image translation and photo retouching methods of course belong to end-to-end methods. Cropping sub-images here is for fast reading and reducing GPU memory usage, which is also a common operation in many low-level tasks. Bicubic-downsampled images are the conditional input of the AGCM part. More training details can be founded in Supp. of the paper.

**Comment by tnt-ooo-tnt** [comment]
@chxy95 
Without modifying your train/test options (yaml), could you let me know which images each directory includes? (like test_hdr_sub includes cropped images from python script)

Thank you for fast reply :)

**Comment by chxy95** [comment]
@tnt-ooo-tnt folder with 'sub' means cropped sub-images are included, and 'bicx' means down-sampled image folder. In AGCM, folder of condition consists of down-sampled images.

**Comment by tnt-ooo-tnt** [comment]
@chxy95
thank you for your kindness, I am closing the issue
