### ISSUE TITLE
Reproduced result of Deep-SRITM

### ISSUE THREAD

**Issue by tnt-ooo-tnt** [chxy95/HDRTVNet#3]
Hi, really appreciate again.

Which source code has been used for the scores of Deep-SRITM in _Table 1_?
1. The matlab code (official)
2. PyTorch version (Link: [https://github.com/greatwallet/Pytorch-Implemented-Deep-SR-ITM.git](https://github.com/greatwallet/Pytorch-Implemented-Deep-SR-ITM.git))
3. Re-written version by authors?

Thank you for your kindness

**Comment by chxy95** [comment]
@tnt-ooo-tnt We reproduce the deep sr-itm by ourselves according to the MatConvNet source code.

**Comment by tnt-ooo-tnt** [comment]
@chxy95 
So the official code with the dataset introduced in HDRTVNet has been used, right?

Thank you for clarification

**Comment by chxy95** [comment]
@tnt-ooo-tnt Yes.

**Comment by tnt-ooo-tnt** [comment]
Thanks a lot

**Comment by chxy95** [comment]
wait a moment... we don't use the official code. we reproduce the deep sr-itm by pytorhc according to the matconvnet source code.  Before train it on our dataset, we have verified the correctness of our reproduction on their dataset and settings.

**Comment by tnt-ooo-tnt** [comment]
@chxy95
Oh I see, thank you again.

Could you share the source codes of SRITM?

If can not, sorry for requesting such a big task :)

**Comment by chxy95** [comment]
@ Sorry, it's not convenient to share the reproduction code.

**Comment by chxy95** [comment]
@tnt-ooo-tnt Sorry, it's not convenient to share the reproduction code.
