### ISSUE TITLE
pdd值问题 ppd = hdrvdp_pix_per_deg( 50, ?, ?);

### ISSUE THREAD

**Issue by wanghu178** [chxy95/HDRTVNet#5]
您好！我想去测试你的图片，但是我不知道pdd值中设置的分辨率以及观看距离是多少，你可以告诉我吗？谢谢您

**Comment by chxy95** [comment]
@wanghu178 ppd=50；hdrvdp3('side-by-side', LQ_img, GT_img, 'rgb-bt.2020', ppd, {'rgb_display', 'led-lcd-wcg'});

**Comment by wanghu178** [comment]
哦哦我明白了，我好憨憨。。 谢谢您！万分感激！
