### ISSUE TITLE
PQEOTF函数的作用

### ISSUE THREAD

**Issue by wanghu178** [chxy95/HDRTVNet#6]
您好！在hdr-vdp3测试中，我看见您用了PQEOTF函数对得到的图像进行处理，但是我在看hdrvdp3的代码时，作者并没有说要使用给函数进行处理然后进行测试（也有可能我没有看到）。请问这是为什么？谢谢您！ 麻烦你好多次了。感激! 感激！

**Comment by chxy95** [comment]
@wanghu178 `The values must be given in absolute luminance units (cd/m^2).`

**Comment by wanghu178** [comment]
Oh oh, I get it. Thank you.
