### ISSUE TITLE
从onedrive上下载的1235张图的训练数据无法打开，请问大家也是这样吗？

### ISSUE THREAD

**Issue by fanld** [chxy95/HDRTVNet#9]

**Comment by dnnyyq** [comment]
me too!  but I downloaded training data (1235 png images) from Baidu Netdisk

**Comment by chxy95** [comment]
The dataset is uploaded after subsection compression since it's too large. Please download the complete training set to unzip.

**Comment by dnnyyq** [comment]
> The dataset is uploaded after subsection compression since it's too large. Please download the complete training set to unzip.

thanks for your response.  the list of downloaded data has four files: 
`-rw-r--r-- 1 root root 12884901888 Dec 24 10:41 training_set.z01
-rw-r--r-- 1 root root 12884901888 Dec 24 10:41 training_set.z02
-rw-r--r-- 1 root root 12884901888 Dec 24 11:02 training_set.z03
-rw-r--r-- 1 root root  4999256771 Dec 17 10:13 training_set.zip`

i concat four files and unzip, but only 287 hdr images, others have unzip error.

 any other subsection？ is all for four files?

**Comment by chxy95** [comment]
@dnnyyq On ubuntu, you need to merge all the subsections to one file first, then unzip it. You can refer to https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux.

**Comment by dnnyyq** [comment]
@ chxy95 this is done by your suggestion ( https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux). thank you! thank you for your work!
